/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  //ignore: constant_identifier_names
  static const IconData water_drop_outline =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
